# Generated by Django 5.2.9 on 2025-12-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaUser',
            fields=[
                ('id', models.UUIDField(db_column='id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('image', models.CharField(blank=True, max_length=1024, null=True)),
                ('profile_description', models.CharField(blank=True, max_length=1024, null=True)),
                ('profile_header_image', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_teacher', models.BooleanField(default=False)),
                ('teaching_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_plan', models.CharField(default='B', max_length=1)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('login_allowed', models.BooleanField(default=True)),
                ('onboarding_passed', models.BooleanField(default=False)),
                ('is_official', models.BooleanField(default=False)),
                ('strike_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('show_interests', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('slug', models.CharField(db_index=True, max_length=255, unique=True)),
                ('hashed_password', models.CharField(max_length=1024)),
                ('study_plan_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users_user',
                'managed': False,
            },
        ),
    ]
