"""empty message

Revision ID: 35726386f14e
Revises: e2369e26e104
Create Date: 2025-12-26 13:29:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "35726386f14e"
down_revision: Union[str, Sequence[str], None] = "0014_rename_taskhistory_id"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop tables section
    # op.drop_table('users_user_friend_requests')
    # op.drop_table('users_studygroup_goals')
    # op.drop_table('users_studygroup_exercises_sets')
    # op.drop_table('users_lessonblock_words')
    # op.drop_table('users_lesson_collecions')
    # op.drop_table('users_grammar_gaps')
    # op.drop_table('users_studygroup_collections')
    # op.drop_table('users_lesson_words')
    # op.drop_table('users_lessonblock_collecions')
    # op.drop_table('users_studygroup_grammar')
    # op.drop_table('users_grammargap_allowed_words')
    # op.drop_table('users_user_groups')
    # op.drop_table('users_studygroup_members')
    # op.drop_table('users_grammargap_allowed_words_form_groups')
    # op.drop_table('authtoken_token')
    # op.drop_table('vocabulary_collection_share_with')
    # op.drop_table('users_task_usage_words')
    # op.drop_table('users_studygroup_lessons')
    # op.drop_table('users_lessonblock_grammar')
    # op.drop_table('users_usersettings_disallow_suggestions_for')
    # op.drop_table('users_studygroup_materials')
    # op.drop_table('exercises_exercisesessiontaskshistory_right_answers_translab2c2')
    # op.drop_table('vocabulary_word_share_with')
    # op.drop_table('users_grammargap_allowed_words_tags')
    # op.drop_table('users_user_user_permissions')
    # op.drop_table('users_lesson_grammar')
    # op.drop_table('users_user_cities')
    # op.drop_table('users_grammargap_allowed_words_translations')
    # op.drop_table('users_user_friends')
    # op.drop_table('users_lesson_tags')
    # op.drop_table('users_grammargap_allowed_words_types')
    # op.drop_table('users_user_interests')

    # Alter column operations
    op.alter_column(
        "achievements_achievement",
        "image",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )

    op.drop_column("achievements_achievement_users_access", "id")

    op.add_column(
        "achievements_achievementgroup",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "achievements_achievementgroup",
        "title",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=128),
        existing_nullable=False,
    )

    op.add_column(
        "chats_attachment",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "chats_attachment",
        "image",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )
    op.alter_column(
        "chats_attachment",
        "file",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )

    op.alter_column(
        "chats_chat",
        "chat_image",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )

    op.drop_column("chats_chat_blocked_users", "id")
    op.drop_column("chats_chat_languages_used", "id")
    op.drop_column("chats_chat_tags", "id")

    op.add_column(
        "chats_chatmember",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "core_platformreview",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "exercises_customexerciseconfiguration",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "exercises_customexerciseconfiguration",
        "content_text",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
    )
    op.alter_column(
        "exercises_customexerciseconfiguration",
        "content_image",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )

    op.drop_column("exercises_customexerciseconfiguration_gaps", "id")

    op.add_column(
        "exercises_customgap",
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "exercises_customgap",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "exercises_customgap",
        "pre_position",
        existing_type=sa.SMALLINT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "exercises_customgap",
        "order_position",
        existing_type=sa.SMALLINT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )

    op.drop_column("exercises_customgap_allowed_words", "id")

    op.alter_column(
        "exercises_exercise",
        "constraint_description",
        existing_type=sa.VARCHAR(length=512),
        nullable=True,
    )
    op.alter_column(
        "exercises_exercise",
        "icon",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )
    op.alter_column(
        "exercises_exercise",
        "slug",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=255),
        existing_nullable=False,
    )

    op.drop_column("exercises_exercise_hints_available", "id")

    op.add_column(
        "exercises_exerciseconfiguration",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "exercises_exerciseconfiguration",
        "translations_mode",
        existing_type=sa.VARCHAR(length=3),
        nullable=True,
    )
    op.alter_column(
        "exercises_exerciseconfiguration",
        "definitions_mode",
        existing_type=sa.VARCHAR(length=3),
        nullable=True,
    )

    op.drop_column("exercises_exerciseconfiguration_hints_available", "id")
    op.drop_column("exercises_exerciseconfiguration_words", "id")
    op.drop_column("exercises_exerciseconfiguration_words_set", "id")

    op.add_column(
        "exercises_exercisesessionhistory",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.drop_column("exercises_exercisesessionhistory", "share_link")

    op.add_column(
        "exercises_exercisesessiontaskshistory",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "exercises_exercisesessiontaskshistory",
        "task_language",
        existing_type=sa.VARCHAR(length=8),
        nullable=True,
    )
    op.drop_column("exercises_exercisesessiontaskshistory", "right_answers_variants")
    # op.drop_column('exercises_exercisesessiontaskshistory', 'input_mode')
    op.drop_column("exercises_exercisesessiontaskshistory", "variants")

    op.drop_column("exercises_exercisesessiontaskshistory_hints_available", "id")
    op.drop_column("exercises_exercisesessiontaskshistory_hints_used", "id")
    op.drop_column(
        "exercises_exercisesessiontaskshistory_right_answers_definitions", "id"
    )
    op.drop_column("exercises_exercisesessiontaskshistory_right_answers_words", "id")

    op.alter_column(
        "exercises_exercisesset",
        "slug",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.drop_column("exercises_exercisesset", "share_link")

    op.add_column(
        "exercises_exercisesset_custom_exercises",
        sa.Column("exerciseset_id", sa.UUID(), nullable=False),
    )
    op.drop_column("exercises_exercisesset_custom_exercises", "id")
    op.drop_column("exercises_exercisesset_custom_exercises", "exercisesset_id")

    op.add_column(
        "exercises_exercisesset_exercises",
        sa.Column("exerciseset_id", sa.UUID(), nullable=False),
    )
    op.drop_column("exercises_exercisesset_exercises", "id")
    op.drop_column("exercises_exercisesset_exercises", "exercisesset_id")

    op.add_column(
        "exercises_exercisesset_words",
        sa.Column("exerciseset_id", sa.UUID(), nullable=False),
    )
    op.drop_column("exercises_exercisesset_words", "id")
    op.drop_column("exercises_exercisesset_words", "exercisesset_id")

    op.add_column(
        "exercises_favoriteexercise",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "exercises_favoriteexerciseset",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "exercises_hint",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "exercises_hint",
        "word_customization_content_needed",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )

    op.add_column(
        "exercises_wordsset",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "exercises_wordsset",
        "slug",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=255),
        existing_nullable=False,
    )

    op.drop_column("exercises_wordsset_words", "id")

    op.add_column(
        "languages_language",
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "languages_language",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "languages_language",
        "country",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
    )
    op.alter_column(
        "languages_language",
        "flag_icon",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )

    op.alter_column(
        "languages_languagecoverimage",
        "image",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=False,
    )
    # op.drop_column('languages_languagecoverimage', 'author_id')

    op.alter_column(
        "languages_userlearninglanguage",
        "level",
        existing_type=sa.VARCHAR(length=2),
        type_=sa.String(length=32),
        existing_nullable=True,
    )
    op.alter_column(
        "languages_userlearninglanguage",
        "slug",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=255),
        existing_nullable=False,
    )

    op.add_column(
        "languages_usernativelanguage",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "languages_usernativelanguage",
        "slug",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=255),
        existing_nullable=False,
    )

    op.add_column(
        "notifications_notification",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.alter_column(
        "users_certificate",
        "file",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=False,
    )

    op.add_column(
        "users_city", sa.Column("modified", sa.DateTime(timezone=True), nullable=True)
    )

    op.add_column(
        "users_complaint",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "users_complaint",
        "comment",
        existing_type=sa.VARCHAR(length=512),
        nullable=True,
    )
    op.drop_column("users_complaint", "author_id")

    op.alter_column(
        "users_confirmationrequest",
        "request_status",
        existing_type=sa.VARCHAR(length=1),
        type_=sa.String(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        "users_confirmationrequest",
        "review",
        existing_type=sa.VARCHAR(length=1024),
        nullable=True,
    )

    op.add_column(
        "users_favoritegrammar",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.alter_column(
        "users_goal", "description", existing_type=sa.VARCHAR(length=128), nullable=True
    )
    op.alter_column(
        "users_goal", "open_access", existing_type=sa.BOOLEAN(), nullable=True
    )

    op.add_column(
        "users_goalmember",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "users_goalmember",
        "goal_status",
        existing_type=sa.VARCHAR(length=3),
        type_=sa.String(length=16),
        existing_nullable=False,
    )
    op.alter_column(
        "users_goalmember",
        "send_notifications_from_others",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )

    op.alter_column(
        "users_grammar", "name", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    op.alter_column(
        "users_grammar",
        "slug",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=255),
        existing_nullable=False,
    )

    op.add_column(
        "users_grammargap",
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "users_grammargap",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "users_interest",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "users_interest",
        "cover",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )

    op.alter_column(
        "users_lesson",
        "description",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
    )
    op.alter_column(
        "users_lesson",
        "cover",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )
    op.drop_column("users_lesson", "share_link")

    op.add_column(
        "users_lessonblock",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "users_lessonblock", "title", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    op.alter_column(
        "users_lessonblock",
        "image",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )
    op.alter_column(
        "users_lessonblock",
        "file",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )

    op.alter_column(
        "users_material", "title", existing_type=sa.VARCHAR(length=32), nullable=True
    )
    op.alter_column(
        "users_material", "text", existing_type=sa.VARCHAR(length=1024), nullable=True
    )
    op.alter_column(
        "users_material",
        "file",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )

    op.add_column(
        "users_sociallink",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "users_strikeseriahistory",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "users_strikeseriahistory",
        "strike_start_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "users_strikeseriahistory",
        "strike_end_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )

    op.drop_column("users_studygroup", "slug")

    op.alter_column(
        "users_studyplan",
        "description",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
    )

    op.add_column(
        "users_subscription",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "users_subscription",
        "enable_notifications",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )

    op.alter_column(
        "users_task",
        "usage_type",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.String(length=8),
        existing_nullable=False,
    )
    op.alter_column(
        "users_task",
        "words_status",
        existing_type=sa.VARCHAR(length=1),
        type_=sa.String(length=16),
        existing_nullable=False,
    )

    op.add_column(
        "users_taskprogress",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "users_taskprogress", "is_finished", existing_type=sa.BOOLEAN(), nullable=True
    )

    op.add_column(
        "users_teacherreview", sa.Column("stars", sa.SmallInteger(), nullable=True)
    )
    op.drop_column("users_teacherreview", "starts")

    op.alter_column(
        "users_user", "first_name", existing_type=sa.VARCHAR(length=32), nullable=True
    )
    op.alter_column(
        "users_user",
        "image",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )
    op.alter_column(
        "users_user",
        "profile_description",
        existing_type=sa.VARCHAR(length=512),
        nullable=True,
    )
    op.alter_column(
        "users_user",
        "profile_header_image",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )
    op.alter_column(
        "users_user",
        "teaching_goal",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )
    op.alter_column(
        "users_user",
        "date_joined",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "users_user",
        "slug",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.drop_column("users_user", "password_backup")

    op.alter_column(
        "users_userissue", "title", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    op.alter_column(
        "users_userissue",
        "level_requested",
        existing_type=sa.VARCHAR(length=2),
        type_=sa.String(length=8),
        existing_nullable=True,
    )

    op.add_column(
        "users_usersettings",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "users_usersettings",
        "allow_buddy_search",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "users_usersettings",
        "allow_subscriptions",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "users_usersettings",
        "words_allow_comments",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "users_usersettings",
        "collections_allow_comments",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "users_usersettings",
        "collections_allow_suggestions",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "users_usersettings",
        "collections_allow_suggestions_notifications",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "users_usersettings",
        "private_account",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "users_usersettings",
        "auto_problematic_words",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "users_usersettings",
        "hide_suggested_content",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "users_usersettings",
        "only_premium_content",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "users_usersettings",
        "words_default_cards_type",
        existing_type=sa.VARCHAR(length=2),
        type_=sa.String(length=8),
        existing_nullable=False,
    )

    op.alter_column(
        "vocabulary_antonym",
        "note",
        existing_type=sa.VARCHAR(length=2048),
        nullable=True,
    )

    op.alter_column(
        "vocabulary_collection",
        "description",
        existing_type=sa.VARCHAR(length=512),
        nullable=True,
    )
    op.alter_column(
        "vocabulary_collection",
        "slug",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=255),
        existing_nullable=False,
    )

    op.drop_column("vocabulary_collection_coauthors", "id")
    op.drop_column("vocabulary_collection_tags", "id")

    op.add_column(
        "vocabulary_collectioncomment_answers",
        sa.Column("collectioncomment_id", sa.UUID(), nullable=False),
    )
    op.add_column(
        "vocabulary_collectioncomment_answers",
        sa.Column("answer_id", sa.UUID(), nullable=False),
    )
    op.drop_column("vocabulary_collectioncomment_answers", "from_collectioncomment_id")
    op.drop_column("vocabulary_collectioncomment_answers", "id")
    op.drop_column("vocabulary_collectioncomment_answers", "to_collectioncomment_id")

    op.drop_column("vocabulary_collectioncomment_dislikes", "id")
    op.drop_column("vocabulary_collectioncomment_likes", "id")

    op.add_column(
        "vocabulary_collectionsubscription",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.alter_column(
        "vocabulary_definition",
        "translation",
        existing_type=sa.VARCHAR(length=512),
        nullable=True,
    )
    op.alter_column(
        "vocabulary_definition",
        "slug",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=255),
        existing_nullable=False,
    )

    op.add_column(
        "vocabulary_derivative",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "vocabulary_favoritecollection",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "vocabulary_favoriteword",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "vocabulary_form",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.alter_column(
        "vocabulary_formgroup",
        "color",
        existing_type=sa.VARCHAR(length=7),
        nullable=True,
    )
    op.alter_column(
        "vocabulary_formgroup",
        "translation",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )
    op.alter_column(
        "vocabulary_formgroup",
        "slug",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=255),
        existing_nullable=False,
    )

    op.alter_column(
        "vocabulary_imageassociation",
        "image",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )

    op.alter_column(
        "vocabulary_premiumrequest",
        "review",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
    )

    op.alter_column(
        "vocabulary_quoteassociation",
        "quote_author",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )

    op.add_column(
        "vocabulary_similar",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.alter_column(
        "vocabulary_synonym",
        "note",
        existing_type=sa.VARCHAR(length=2048),
        nullable=True,
    )

    op.alter_column(
        "vocabulary_usageexample",
        "translation",
        existing_type=sa.VARCHAR(length=512),
        nullable=True,
    )
    op.alter_column(
        "vocabulary_usageexample",
        "slug",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=255),
        existing_nullable=False,
    )

    op.add_column(
        "vocabulary_viewcollection",
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "vocabulary_viewcollection",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "vocabulary_viewword",
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "vocabulary_viewword",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.alter_column(
        "vocabulary_word", "note", existing_type=sa.VARCHAR(length=2048), nullable=True
    )
    op.alter_column(
        "vocabulary_word",
        "slug",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=255),
        existing_nullable=False,
    )

    op.drop_column("vocabulary_word_tags", "id")
    op.drop_column("vocabulary_word_types", "id")

    op.add_column(
        "vocabulary_wordactivityhistory",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "vocabulary_wordactivityhistory",
        "previous_activity_progress",
        existing_type=sa.SMALLINT(),
        nullable=True,
    )
    op.alter_column(
        "vocabulary_wordactivityhistory",
        "new_activity_progress",
        existing_type=sa.SMALLINT(),
        nullable=True,
    )

    op.add_column(
        "vocabulary_wordapprove",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "vocabulary_wordcomment_answers",
        sa.Column("wordcomment_id", sa.UUID(), nullable=False),
    )
    op.add_column(
        "vocabulary_wordcomment_answers",
        sa.Column("answer_id", sa.UUID(), nullable=False),
    )
    op.drop_column("vocabulary_wordcomment_answers", "from_wordcomment_id")
    op.drop_column("vocabulary_wordcomment_answers", "id")
    op.drop_column("vocabulary_wordcomment_answers", "to_wordcomment_id")

    op.drop_column("vocabulary_wordcomment_dislikes", "id")
    op.drop_column("vocabulary_wordcomment_likes", "id")

    op.add_column(
        "vocabulary_worddefinitions",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "vocabulary_wordimageassociations",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "vocabulary_wordquoteassociations",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "vocabulary_wordsformgroups",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "vocabulary_wordsincollections",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.add_column(
        "vocabulary_wordssuggestedtocollections",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.alter_column(
        "vocabulary_wordtranslation",
        "slug",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=255),
        existing_nullable=False,
    )

    op.add_column(
        "vocabulary_wordtranslations",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.alter_column(
        "vocabulary_wordtype",
        "slug",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=255),
        existing_nullable=False,
    )

    op.add_column(
        "vocabulary_wordusageexamples",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_table(
        "exercises_exercisesessiontaskshistory_right_answers_translations",
        sa.Column("exercisesessiontaskshistory_id", sa.UUID(), nullable=False),
        sa.Column("translation_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercisesessiontaskshistory_id"],
            ["exercises_exercisesessiontaskshistory.id"],
            name=op.f(
                "fk_exercises_exercisesessiontaskshistory_right_answers_translations_exercisesessiontaskshistory_id_exercises_exercisesessiontaskshistory"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["translation_id"],
            ["vocabulary_wordtranslation.id"],
            name=op.f(
                "fk_exercises_exercisesessiontaskshistory_right_answers_translations_translation_id_vocabulary_wordtranslation"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "exercisesessiontaskshistory_id",
            "translation_id",
            name=op.f(
                "pk_exercises_exercisesessiontaskshistory_right_answers_translations"
            ),
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Note: Operations are listed in reverse order of the upgrade()

    op.drop_table("exercises_exercisesessiontaskshistory_right_answers_translations")

    # Re-add columns that were dropped
    op.add_column(
        "vocabulary_wordusageexamples",
        sa.Column("modified", sa.DateTime(timezone=True), nullable=True),
    )

    op.alter_column(
        "vocabulary_wordtype",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )

    op.drop_column("vocabulary_wordtranslations", "modified")
    op.alter_column(
        "vocabulary_wordtranslation",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )

    op.drop_column("vocabulary_wordssuggestedtocollections", "modified")

    op.drop_column("vocabulary_wordsincollections", "modified")

    op.drop_column("vocabulary_wordsformgroups", "modified")

    op.drop_column("vocabulary_wordquoteassociations", "modified")

    op.drop_column("vocabulary_wordimageassociations", "modified")

    op.drop_column("vocabulary_worddefinitions", "modified")

    # Re-add dropped columns for comment tables (with their original constraints)
    op.add_column(
        "vocabulary_wordcomment_likes",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "vocabulary_wordcomment_dislikes",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )

    # Restore original column structure for vocabulary_wordcomment_answers
    op.add_column(
        "vocabulary_wordcomment_answers",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "vocabulary_wordcomment_answers",
        sa.Column("from_wordcomment_id", sa.UUID(), nullable=False),
    )
    op.add_column(
        "vocabulary_wordcomment_answers",
        sa.Column("to_wordcomment_id", sa.UUID(), nullable=False),
    )
    op.drop_column("vocabulary_wordcomment_answers", "answer_id")
    op.drop_column("vocabulary_wordcomment_answers", "wordcomment_id")

    op.drop_column("vocabulary_wordapprove", "modified")

    # Restore original column constraints
    op.alter_column(
        "vocabulary_wordactivityhistory",
        "new_activity_progress",
        existing_type=sa.SMALLINT(),
        nullable=False,
    )
    op.alter_column(
        "vocabulary_wordactivityhistory",
        "previous_activity_progress",
        existing_type=sa.SMALLINT(),
        nullable=False,
    )
    op.drop_column("vocabulary_wordactivityhistory", "modified")

    # Re-add id columns for junction tables
    op.add_column(
        "vocabulary_word_types",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "vocabulary_word_tags",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )

    op.alter_column(
        "vocabulary_word",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "vocabulary_word", "note", existing_type=sa.VARCHAR(length=2048), nullable=False
    )

    op.drop_column("vocabulary_viewword", "modified")
    op.drop_column("vocabulary_viewword", "created")

    op.drop_column("vocabulary_viewcollection", "modified")
    op.drop_column("vocabulary_viewcollection", "created")

    op.alter_column(
        "vocabulary_usageexample",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "vocabulary_usageexample",
        "translation",
        existing_type=sa.VARCHAR(length=512),
        nullable=False,
    )

    op.alter_column(
        "vocabulary_synonym",
        "note",
        existing_type=sa.VARCHAR(length=2048),
        nullable=False,
    )

    op.drop_column("vocabulary_similar", "modified")

    op.alter_column(
        "vocabulary_quoteassociation",
        "quote_author",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )

    op.alter_column(
        "vocabulary_premiumrequest",
        "review",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
    )

    op.alter_column(
        "vocabulary_imageassociation",
        "image",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )

    op.alter_column(
        "vocabulary_formgroup",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "vocabulary_formgroup",
        "translation",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.alter_column(
        "vocabulary_formgroup",
        "color",
        existing_type=sa.VARCHAR(length=7),
        nullable=False,
    )

    op.drop_column("vocabulary_form", "modified")

    op.drop_column("vocabulary_favoriteword", "modified")

    op.drop_column("vocabulary_favoritecollection", "modified")

    op.drop_column("vocabulary_derivative", "modified")

    op.alter_column(
        "vocabulary_definition",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "vocabulary_definition",
        "translation",
        existing_type=sa.VARCHAR(length=512),
        nullable=False,
    )

    op.drop_column("vocabulary_collectionsubscription", "modified")

    # Re-add id columns for collection comment tables
    op.add_column(
        "vocabulary_collectioncomment_likes",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "vocabulary_collectioncomment_dislikes",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )

    # Restore original column structure for vocabulary_collectioncomment_answers
    op.add_column(
        "vocabulary_collectioncomment_answers",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "vocabulary_collectioncomment_answers",
        sa.Column("from_collectioncomment_id", sa.UUID(), nullable=False),
    )
    op.add_column(
        "vocabulary_collectioncomment_answers",
        sa.Column("to_collectioncomment_id", sa.UUID(), nullable=False),
    )
    op.drop_column("vocabulary_collectioncomment_answers", "answer_id")
    op.drop_column("vocabulary_collectioncomment_answers", "collectioncomment_id")

    # Re-add id columns for junction tables
    op.add_column(
        "vocabulary_collection_tags",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "vocabulary_collection_coauthors",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )

    op.alter_column(
        "vocabulary_collection",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "vocabulary_collection",
        "description",
        existing_type=sa.VARCHAR(length=512),
        nullable=False,
    )

    op.alter_column(
        "vocabulary_antonym",
        "note",
        existing_type=sa.VARCHAR(length=2048),
        nullable=False,
    )

    # Users table operations (reverse order)
    op.alter_column(
        "users_usersettings",
        "words_default_cards_type",
        existing_type=sa.String(length=8),
        type_=sa.VARCHAR(length=2),
        existing_nullable=False,
    )
    op.alter_column(
        "users_usersettings",
        "only_premium_content",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "users_usersettings",
        "hide_suggested_content",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "users_usersettings",
        "auto_problematic_words",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "users_usersettings",
        "private_account",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "users_usersettings",
        "collections_allow_suggestions_notifications",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "users_usersettings",
        "collections_allow_suggestions",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "users_usersettings",
        "collections_allow_comments",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "users_usersettings",
        "words_allow_comments",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "users_usersettings",
        "allow_subscriptions",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "users_usersettings",
        "allow_buddy_search",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.drop_column("users_usersettings", "modified")

    op.alter_column(
        "users_userissue",
        "level_requested",
        existing_type=sa.String(length=8),
        type_=sa.VARCHAR(length=2),
        existing_nullable=True,
    )
    op.alter_column(
        "users_userissue", "title", existing_type=sa.VARCHAR(length=64), nullable=False
    )

    op.add_column(
        "users_user",
        sa.Column(
            "password_backup",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "users_user",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "users_user",
        "date_joined",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "users_user",
        "teaching_goal",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.alter_column(
        "users_user",
        "profile_header_image",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "users_user",
        "profile_description",
        existing_type=sa.VARCHAR(length=512),
        nullable=False,
    )
    op.alter_column(
        "users_user",
        "image",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "users_user", "first_name", existing_type=sa.VARCHAR(length=32), nullable=False
    )

    op.add_column(
        "users_teacherreview",
        sa.Column("starts", sa.SMALLINT(), autoincrement=False, nullable=True),
    )
    op.drop_column("users_teacherreview", "stars")

    op.alter_column(
        "users_taskprogress", "is_finished", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_column("users_taskprogress", "modified")

    op.alter_column(
        "users_task",
        "words_status",
        existing_type=sa.String(length=16),
        type_=sa.VARCHAR(length=1),
        existing_nullable=False,
    )
    op.alter_column(
        "users_task",
        "usage_type",
        existing_type=sa.String(length=8),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )

    op.alter_column(
        "users_subscription",
        "enable_notifications",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.drop_column("users_subscription", "modified")

    op.alter_column(
        "users_studyplan",
        "description",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
    )

    op.add_column(
        "users_studygroup",
        sa.Column("slug", sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    )

    op.alter_column(
        "users_strikeseriahistory",
        "strike_end_date",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DATE(),
        existing_nullable=True,
    )
    op.alter_column(
        "users_strikeseriahistory",
        "strike_start_date",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.drop_column("users_strikeseriahistory", "modified")

    op.drop_column("users_sociallink", "modified")

    op.alter_column(
        "users_material",
        "file",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "users_material", "text", existing_type=sa.VARCHAR(length=1024), nullable=False
    )
    op.alter_column(
        "users_material", "title", existing_type=sa.VARCHAR(length=32), nullable=False
    )

    op.alter_column(
        "users_lessonblock",
        "file",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "users_lessonblock",
        "image",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "users_lessonblock",
        "title",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.drop_column("users_lessonblock", "modified")

    op.add_column(
        "users_lesson",
        sa.Column("share_link", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "users_lesson",
        "cover",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "users_lesson",
        "description",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
    )

    op.alter_column(
        "users_interest",
        "cover",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.drop_column("users_interest", "modified")

    op.drop_column("users_grammargap", "modified")
    op.drop_column("users_grammargap", "created")

    op.alter_column(
        "users_grammar",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "users_grammar", "name", existing_type=sa.VARCHAR(length=64), nullable=False
    )

    op.alter_column(
        "users_goalmember",
        "send_notifications_from_others",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "users_goalmember",
        "goal_status",
        existing_type=sa.String(length=16),
        type_=sa.VARCHAR(length=3),
        existing_nullable=False,
    )
    op.drop_column("users_goalmember", "modified")

    op.alter_column(
        "users_goal", "open_access", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "users_goal",
        "description",
        existing_type=sa.VARCHAR(length=128),
        nullable=False,
    )

    op.drop_column("users_favoritegrammar", "modified")

    op.alter_column(
        "users_confirmationrequest",
        "review",
        existing_type=sa.VARCHAR(length=1024),
        nullable=False,
    )
    op.alter_column(
        "users_confirmationrequest",
        "request_status",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=1),
        existing_nullable=False,
    )

    op.add_column(
        "users_complaint",
        sa.Column("author_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "users_complaint",
        "comment",
        existing_type=sa.VARCHAR(length=512),
        nullable=False,
    )
    op.drop_column("users_complaint", "modified")

    op.drop_column("users_city", "modified")

    op.alter_column(
        "users_certificate",
        "file",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )

    op.drop_column("notifications_notification", "modified")

    op.alter_column(
        "languages_usernativelanguage",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    op.drop_column("languages_usernativelanguage", "modified")

    op.alter_column(
        "languages_userlearninglanguage",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "languages_userlearninglanguage",
        "level",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=2),
        existing_nullable=True,
    )

    # op.add_column('languages_languagecoverimage', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=True))
    op.alter_column(
        "languages_languagecoverimage",
        "image",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )

    op.alter_column(
        "languages_language",
        "flag_icon",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "languages_language",
        "country",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
    )
    op.drop_column("languages_language", "modified")
    op.drop_column("languages_language", "created")

    op.add_column(
        "exercises_wordsset_words",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )

    op.alter_column(
        "exercises_wordsset",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    op.drop_column("exercises_wordsset", "modified")

    op.alter_column(
        "exercises_hint",
        "word_customization_content_needed",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.drop_column("exercises_hint", "modified")

    op.drop_column("exercises_favoriteexerciseset", "modified")
    op.drop_column("exercises_favoriteexercise", "modified")

    # Re-add columns for exerciseset tables
    op.add_column(
        "exercises_exercisesset_words",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "exercises_exercisesset_words",
        sa.Column("exercisesset_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_column("exercises_exercisesset_words", "exerciseset_id")

    op.add_column(
        "exercises_exercisesset_exercises",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "exercises_exercisesset_exercises",
        sa.Column("exercisesset_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_column("exercises_exercisesset_exercises", "exerciseset_id")

    op.add_column(
        "exercises_exercisesset_custom_exercises",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "exercises_exercisesset_custom_exercises",
        sa.Column("exercisesset_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_column("exercises_exercisesset_custom_exercises", "exerciseset_id")

    op.add_column(
        "exercises_exercisesset",
        sa.Column("share_link", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "exercises_exercisesset",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )

    # Re-add id columns for exercisesessiontaskshistory tables
    op.add_column(
        "exercises_exercisesessiontaskshistory_right_answers_words",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "exercises_exercisesessiontaskshistory_right_answers_definitions",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "exercises_exercisesessiontaskshistory_hints_used",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "exercises_exercisesessiontaskshistory_hints_available",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )

    # Re-add columns to exercisesessiontaskshistory
    op.add_column(
        "exercises_exercisesessiontaskshistory",
        sa.Column(
            "variants",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # op.add_column('exercises_exercisesessiontaskshistory', sa.Column('input_mode', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.add_column(
        "exercises_exercisesessiontaskshistory",
        sa.Column(
            "right_answers_variants",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "exercises_exercisesessiontaskshistory",
        "task_language",
        existing_type=sa.VARCHAR(length=8),
        nullable=False,
    )
    op.drop_column("exercises_exercisesessiontaskshistory", "modified")

    op.add_column(
        "exercises_exercisesessionhistory",
        sa.Column("share_link", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_column("exercises_exercisesessionhistory", "modified")

    # Re-add id columns for exerciseconfiguration tables
    op.add_column(
        "exercises_exerciseconfiguration_words_set",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "exercises_exerciseconfiguration_words",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "exercises_exerciseconfiguration_hints_available",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )

    op.alter_column(
        "exercises_exerciseconfiguration",
        "definitions_mode",
        existing_type=sa.VARCHAR(length=3),
        nullable=False,
    )
    op.alter_column(
        "exercises_exerciseconfiguration",
        "translations_mode",
        existing_type=sa.VARCHAR(length=3),
        nullable=False,
    )
    op.drop_column("exercises_exerciseconfiguration", "modified")

    op.add_column(
        "exercises_exercise_hints_available",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )

    op.alter_column(
        "exercises_exercise",
        "slug",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "exercises_exercise",
        "icon",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "exercises_exercise",
        "constraint_description",
        existing_type=sa.VARCHAR(length=512),
        nullable=False,
    )

    op.add_column(
        "exercises_customgap_allowed_words",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )

    op.alter_column(
        "exercises_customgap",
        "order_position",
        existing_type=sa.Integer(),
        type_=sa.SMALLINT(),
        existing_nullable=False,
    )
    op.alter_column(
        "exercises_customgap",
        "pre_position",
        existing_type=sa.Integer(),
        type_=sa.SMALLINT(),
        existing_nullable=False,
    )
    op.drop_column("exercises_customgap", "modified")
    op.drop_column("exercises_customgap", "created")

    op.add_column(
        "exercises_customexerciseconfiguration_gaps",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )

    op.alter_column(
        "exercises_customexerciseconfiguration",
        "content_image",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "exercises_customexerciseconfiguration",
        "content_text",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
    )
    op.drop_column("exercises_customexerciseconfiguration", "modified")

    op.drop_column("core_platformreview", "modified")

    op.drop_column("chats_chatmember", "modified")

    op.add_column(
        "chats_chat_tags",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "chats_chat_languages_used",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "chats_chat_blocked_users",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )

    op.alter_column(
        "chats_chat",
        "chat_image",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )

    op.alter_column(
        "chats_attachment",
        "file",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "chats_attachment",
        "image",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.drop_column("chats_attachment", "modified")

    op.alter_column(
        "achievements_achievementgroup",
        "title",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.drop_column("achievements_achievementgroup", "modified")

    op.add_column(
        "achievements_achievement_users_access",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
    )

    op.alter_column(
        "achievements_achievement",
        "image",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )

    # Re-create all the dropped tables
    # This would require the full original table definitions with all columns, constraints, indexes
    # Since we don't have the original definitions, we can only list the table names

    op.create_table(
        "users_user_interests",
        # Original table definition would go here
    )

    op.create_table(
        "users_grammargap_allowed_words_types",
        # Original table definition would go here
    )

    op.create_table(
        "users_lesson_tags",
        # Original table definition would go here
    )

    op.create_table(
        "users_user_friends",
        # Original table definition would go here
    )

    op.create_table(
        "users_grammargap_allowed_words_translations",
        # Original table definition would go here
    )

    op.create_table(
        "users_user_cities",
        # Original table definition would go here
    )

    op.create_table(
        "users_lesson_grammar",
        # Original table definition would go here
    )

    op.create_table(
        "users_user_user_permissions",
        # Original table definition would go here
    )

    op.create_table(
        "users_grammargap_allowed_words_tags",
        # Original table definition would go here
    )

    op.create_table(
        "vocabulary_word_share_with",
        # Original table definition would go here
    )

    op.create_table(
        "exercises_exercisesessiontaskshistory_right_answers_translab2c2",
        # Original table definition would go here
    )

    op.create_table(
        "users_studygroup_materials",
        # Original table definition would go here
    )

    op.create_table(
        "users_usersettings_disallow_suggestions_for",
        # Original table definition would go here
    )

    op.create_table(
        "users_lessonblock_grammar",
        # Original table definition would go here
    )

    op.create_table(
        "users_studygroup_lessons",
        # Original table definition would go here
    )

    op.create_table(
        "users_task_usage_words",
        # Original table definition would go here
    )

    op.create_table(
        "vocabulary_collection_share_with",
        # Original table definition would go here
    )

    op.create_table(
        "authtoken_token",
        # Original table definition would go here
    )

    op.create_table(
        "users_grammargap_allowed_words_form_groups",
        # Original table definition would go here
    )

    op.create_table(
        "users_studygroup_members",
        # Original table definition would go here
    )

    op.create_table(
        "users_user_groups",
        # Original table definition would go here
    )

    op.create_table(
        "users_grammargap_allowed_words",
        # Original table definition would go here
    )

    op.create_table(
        "users_studygroup_grammar",
        # Original table definition would go here
    )

    op.create_table(
        "users_lessonblock_collecions",
        # Original table definition would go here
    )

    op.create_table(
        "users_lesson_words",
        # Original table definition would go here
    )

    op.create_table(
        "users_studygroup_collections",
        # Original table definition would go here
    )

    op.create_table(
        "users_grammar_gaps",
        # Original table definition would go here
    )

    op.create_table(
        "users_lesson_collecions",
        # Original table definition would go here
    )

    op.create_table(
        "users_lessonblock_words",
        # Original table definition would go here
    )

    op.create_table(
        "users_studygroup_exercises_sets",
        # Original table definition would go here
    )

    op.create_table(
        "users_studygroup_goals",
        # Original table definition would go here
    )

    op.create_table(
        "users_user_friend_requests",
        # Original table definition would go here
    )

    # ### end Alembic commands ###
